deploy-image:
  image: rabbitmq:3-management
  service:
    port: 15672
  persistence:
    enabled: true
    size: 1Gi
    mountPath: /var/lib/rabbitmq
  ingress:
    enabled: true
  resources:
    limits:
      cpu: "2"
      memory: &test 1Gi
    requests: 
      cpu: 500m
      memory: 512Mi
