apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy-image.fullname" . }}
  labels:
    {{- include "deploy-image.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: port-1
  selector:
    {{- include "deploy-image.selectorLabels" . | nindent 4 }}
